<!DOCTYPE html>
<html lang="en" data-theme="dark">
    <cfoutput>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>#page.meta.title# -  LuCLI Documentation</title>
    <cfinclude template="partials/head.cfm">
    <link rel="stylesheet" href="/css/docs.css">

</head>
<body class="docs-body">
    <cfinclude template="partials/nav.cfm">


    <div class="docs-layout">
        <!-- Left Sidebar Navigation -->
        <aside class="sidebar">
            #data.navigation#
        </aside>

        <!-- Main Content Area -->
        <main class="main-content">
            <div class="content-header">
                <h1 class="content-title">#page.meta.title#</h1>
                <!--- {{#if description}}
                <p class="content-description">{{description}}</p>
                {{/if}} --->
            </div>

            <div class="content-body">
                #content#

                <!-- Docs prev/next pagination (driven by Markspresso meta: prev_url/next_url) -->
                <cfif (structKeyExists(data, "prev_url") and len(data.prev_url)) or (structKeyExists(data, "next_url") and len(data.next_url))>
                    <nav class="docs-pagination">
                        <cfif structKeyExists(data, "prev_url") and len(data.prev_url)>
                            <a href="#data.prev_url#" class="docs-pagination__link docs-pagination__prev">&larr; #htmlEditFormat(data.prev_title)#</a>
                        </cfif>
                        <cfif structKeyExists(data, "next_url") and len(data.next_url)>
                            <a href="#data.next_url#" class="docs-pagination__link docs-pagination__next">#htmlEditFormat(data.next_title)# &rarr;</a>
                        </cfif>
                    </nav>
                </cfif>
            </div>
        </main>

        <!-- Right Table of Contents -->
        <aside class="toc-sidebar">
            <h3 class="toc-title">On This Page</h3>
            <ul class="toc-list">
                <!-- Table of contents will be auto-generated by JavaScript -->
            </ul>
        </aside>
    </div>
    

    <cfinclude template="partials/footer.cfm">
    <script src="/js/main.js"></script>
    </cfoutput>
</body>
</html>
